services:
  backend:
    build:
      context: ./backend
    # ports:
    #   - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: pnpm run dev
